// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public interface DeregisterGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.DeregisterGraphResponse)
    com.google.protobuf.MessageOrBuilder {
}
