// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public interface ExecutorOptsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ExecutorOpts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool record_costs = 1;</code>
   */
  boolean getRecordCosts();

  /**
   * <code>optional bool record_timeline = 3;</code>
   */
  boolean getRecordTimeline();
}
