// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

/**
 * Protobuf type {@code tensorflow.GetStatusResponse}
 */
public  final class GetStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.GetStatusResponse)
    GetStatusResponseOrBuilder {
  // Use GetStatusResponse.newBuilder() to construct.
  private GetStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStatusResponse() {
    deviceAttributes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GetStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              deviceAttributes_ = new java.util.ArrayList<org.tensorflow.framework.DeviceAttributes>();
              mutable_bitField0_ |= 0x00000001;
            }
            deviceAttributes_.add(
                input.readMessage(org.tensorflow.framework.DeviceAttributes.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        deviceAttributes_ = java.util.Collections.unmodifiableList(deviceAttributes_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_GetStatusResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_GetStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.GetStatusResponse.class, org.tensorflow.distruntime.GetStatusResponse.Builder.class);
  }

  public static final int DEVICE_ATTRIBUTES_FIELD_NUMBER = 1;
  private java.util.List<org.tensorflow.framework.DeviceAttributes> deviceAttributes_;
  /**
   * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
   */
  public java.util.List<org.tensorflow.framework.DeviceAttributes> getDeviceAttributesList() {
    return deviceAttributes_;
  }
  /**
   * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
   */
  public java.util.List<? extends org.tensorflow.framework.DeviceAttributesOrBuilder> 
      getDeviceAttributesOrBuilderList() {
    return deviceAttributes_;
  }
  /**
   * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
   */
  public int getDeviceAttributesCount() {
    return deviceAttributes_.size();
  }
  /**
   * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
   */
  public org.tensorflow.framework.DeviceAttributes getDeviceAttributes(int index) {
    return deviceAttributes_.get(index);
  }
  /**
   * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
   */
  public org.tensorflow.framework.DeviceAttributesOrBuilder getDeviceAttributesOrBuilder(
      int index) {
    return deviceAttributes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < deviceAttributes_.size(); i++) {
      output.writeMessage(1, deviceAttributes_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < deviceAttributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, deviceAttributes_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.GetStatusResponse)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.GetStatusResponse other = (org.tensorflow.distruntime.GetStatusResponse) obj;

    boolean result = true;
    result = result && getDeviceAttributesList()
        .equals(other.getDeviceAttributesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getDeviceAttributesCount() > 0) {
      hash = (37 * hash) + DEVICE_ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceAttributesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.GetStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.GetStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.GetStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.GetStatusResponse)
      org.tensorflow.distruntime.GetStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_GetStatusResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_GetStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.GetStatusResponse.class, org.tensorflow.distruntime.GetStatusResponse.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.GetStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDeviceAttributesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (deviceAttributesBuilder_ == null) {
        deviceAttributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        deviceAttributesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.WorkerProtos.internal_static_tensorflow_GetStatusResponse_descriptor;
    }

    public org.tensorflow.distruntime.GetStatusResponse getDefaultInstanceForType() {
      return org.tensorflow.distruntime.GetStatusResponse.getDefaultInstance();
    }

    public org.tensorflow.distruntime.GetStatusResponse build() {
      org.tensorflow.distruntime.GetStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.distruntime.GetStatusResponse buildPartial() {
      org.tensorflow.distruntime.GetStatusResponse result = new org.tensorflow.distruntime.GetStatusResponse(this);
      int from_bitField0_ = bitField0_;
      if (deviceAttributesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          deviceAttributes_ = java.util.Collections.unmodifiableList(deviceAttributes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deviceAttributes_ = deviceAttributes_;
      } else {
        result.deviceAttributes_ = deviceAttributesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.GetStatusResponse) {
        return mergeFrom((org.tensorflow.distruntime.GetStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.GetStatusResponse other) {
      if (other == org.tensorflow.distruntime.GetStatusResponse.getDefaultInstance()) return this;
      if (deviceAttributesBuilder_ == null) {
        if (!other.deviceAttributes_.isEmpty()) {
          if (deviceAttributes_.isEmpty()) {
            deviceAttributes_ = other.deviceAttributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeviceAttributesIsMutable();
            deviceAttributes_.addAll(other.deviceAttributes_);
          }
          onChanged();
        }
      } else {
        if (!other.deviceAttributes_.isEmpty()) {
          if (deviceAttributesBuilder_.isEmpty()) {
            deviceAttributesBuilder_.dispose();
            deviceAttributesBuilder_ = null;
            deviceAttributes_ = other.deviceAttributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            deviceAttributesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeviceAttributesFieldBuilder() : null;
          } else {
            deviceAttributesBuilder_.addAllMessages(other.deviceAttributes_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.distruntime.GetStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.distruntime.GetStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.tensorflow.framework.DeviceAttributes> deviceAttributes_ =
      java.util.Collections.emptyList();
    private void ensureDeviceAttributesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        deviceAttributes_ = new java.util.ArrayList<org.tensorflow.framework.DeviceAttributes>(deviceAttributes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.DeviceAttributes, org.tensorflow.framework.DeviceAttributes.Builder, org.tensorflow.framework.DeviceAttributesOrBuilder> deviceAttributesBuilder_;

    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public java.util.List<org.tensorflow.framework.DeviceAttributes> getDeviceAttributesList() {
      if (deviceAttributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deviceAttributes_);
      } else {
        return deviceAttributesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public int getDeviceAttributesCount() {
      if (deviceAttributesBuilder_ == null) {
        return deviceAttributes_.size();
      } else {
        return deviceAttributesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public org.tensorflow.framework.DeviceAttributes getDeviceAttributes(int index) {
      if (deviceAttributesBuilder_ == null) {
        return deviceAttributes_.get(index);
      } else {
        return deviceAttributesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder setDeviceAttributes(
        int index, org.tensorflow.framework.DeviceAttributes value) {
      if (deviceAttributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.set(index, value);
        onChanged();
      } else {
        deviceAttributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder setDeviceAttributes(
        int index, org.tensorflow.framework.DeviceAttributes.Builder builderForValue) {
      if (deviceAttributesBuilder_ == null) {
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        deviceAttributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder addDeviceAttributes(org.tensorflow.framework.DeviceAttributes value) {
      if (deviceAttributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.add(value);
        onChanged();
      } else {
        deviceAttributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder addDeviceAttributes(
        int index, org.tensorflow.framework.DeviceAttributes value) {
      if (deviceAttributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.add(index, value);
        onChanged();
      } else {
        deviceAttributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder addDeviceAttributes(
        org.tensorflow.framework.DeviceAttributes.Builder builderForValue) {
      if (deviceAttributesBuilder_ == null) {
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.add(builderForValue.build());
        onChanged();
      } else {
        deviceAttributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder addDeviceAttributes(
        int index, org.tensorflow.framework.DeviceAttributes.Builder builderForValue) {
      if (deviceAttributesBuilder_ == null) {
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        deviceAttributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder addAllDeviceAttributes(
        java.lang.Iterable<? extends org.tensorflow.framework.DeviceAttributes> values) {
      if (deviceAttributesBuilder_ == null) {
        ensureDeviceAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deviceAttributes_);
        onChanged();
      } else {
        deviceAttributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder clearDeviceAttributes() {
      if (deviceAttributesBuilder_ == null) {
        deviceAttributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        deviceAttributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public Builder removeDeviceAttributes(int index) {
      if (deviceAttributesBuilder_ == null) {
        ensureDeviceAttributesIsMutable();
        deviceAttributes_.remove(index);
        onChanged();
      } else {
        deviceAttributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public org.tensorflow.framework.DeviceAttributes.Builder getDeviceAttributesBuilder(
        int index) {
      return getDeviceAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public org.tensorflow.framework.DeviceAttributesOrBuilder getDeviceAttributesOrBuilder(
        int index) {
      if (deviceAttributesBuilder_ == null) {
        return deviceAttributes_.get(index);  } else {
        return deviceAttributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public java.util.List<? extends org.tensorflow.framework.DeviceAttributesOrBuilder> 
         getDeviceAttributesOrBuilderList() {
      if (deviceAttributesBuilder_ != null) {
        return deviceAttributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deviceAttributes_);
      }
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public org.tensorflow.framework.DeviceAttributes.Builder addDeviceAttributesBuilder() {
      return getDeviceAttributesFieldBuilder().addBuilder(
          org.tensorflow.framework.DeviceAttributes.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public org.tensorflow.framework.DeviceAttributes.Builder addDeviceAttributesBuilder(
        int index) {
      return getDeviceAttributesFieldBuilder().addBuilder(
          index, org.tensorflow.framework.DeviceAttributes.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.DeviceAttributes device_attributes = 1;</code>
     */
    public java.util.List<org.tensorflow.framework.DeviceAttributes.Builder> 
         getDeviceAttributesBuilderList() {
      return getDeviceAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.DeviceAttributes, org.tensorflow.framework.DeviceAttributes.Builder, org.tensorflow.framework.DeviceAttributesOrBuilder> 
        getDeviceAttributesFieldBuilder() {
      if (deviceAttributesBuilder_ == null) {
        deviceAttributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tensorflow.framework.DeviceAttributes, org.tensorflow.framework.DeviceAttributes.Builder, org.tensorflow.framework.DeviceAttributesOrBuilder>(
                deviceAttributes_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        deviceAttributes_ = null;
      }
      return deviceAttributesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.GetStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.GetStatusResponse)
  private static final org.tensorflow.distruntime.GetStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.GetStatusResponse();
  }

  public static org.tensorflow.distruntime.GetStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetStatusResponse>() {
    public GetStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStatusResponse> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.distruntime.GetStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

