// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public interface RunGraphResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunGraphResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensor recv = 1;</code>
   */
  java.util.List<org.tensorflow.distruntime.NamedTensor> 
      getRecvList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensor recv = 1;</code>
   */
  org.tensorflow.distruntime.NamedTensor getRecv(int index);
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensor recv = 1;</code>
   */
  int getRecvCount();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensor recv = 1;</code>
   */
  java.util.List<? extends org.tensorflow.distruntime.NamedTensorOrBuilder> 
      getRecvOrBuilderList();
  /**
   * <pre>
   * A list of tensors corresponding to those requested by
   * `RunGraphRequest.recv_key`.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensor recv = 1;</code>
   */
  org.tensorflow.distruntime.NamedTensorOrBuilder getRecvOrBuilder(
      int index);

  /**
   * <pre>
   * If the request asked for execution stats, these are returned here.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  boolean hasStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, these are returned here.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStats getStepStats();
  /**
   * <pre>
   * If the request asked for execution stats, these are returned here.
   * </pre>
   *
   * <code>optional .tensorflow.StepStats step_stats = 2;</code>
   */
  org.tensorflow.framework.StepStatsOrBuilder getStepStatsOrBuilder();
}
