// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master.proto

package org.tensorflow.distruntime;

/**
 * Protobuf type {@code tensorflow.RunStepRequest}
 */
public  final class RunStepRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.RunStepRequest)
    RunStepRequestOrBuilder {
  // Use RunStepRequest.newBuilder() to construct.
  private RunStepRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RunStepRequest() {
    sessionHandle_ = "";
    feed_ = java.util.Collections.emptyList();
    fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RunStepRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionHandle_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              feed_ = new java.util.ArrayList<org.tensorflow.framework.NamedTensorProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            feed_.add(
                input.readMessage(org.tensorflow.framework.NamedTensorProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              fetch_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            fetch_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              target_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            target_.add(s);
            break;
          }
          case 42: {
            org.tensorflow.framework.RunOptions.Builder subBuilder = null;
            if (options_ != null) {
              subBuilder = options_.toBuilder();
            }
            options_ = input.readMessage(org.tensorflow.framework.RunOptions.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(options_);
              options_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        feed_ = java.util.Collections.unmodifiableList(feed_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        fetch_ = fetch_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        target_ = target_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_RunStepRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_RunStepRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.distruntime.RunStepRequest.class, org.tensorflow.distruntime.RunStepRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_HANDLE_FIELD_NUMBER = 1;
  private volatile java.lang.Object sessionHandle_;
  /**
   * <pre>
   * REQUIRED: session_handle must be returned by a CreateSession call
   * to the same master service.
   * </pre>
   *
   * <code>optional string session_handle = 1;</code>
   */
  public java.lang.String getSessionHandle() {
    java.lang.Object ref = sessionHandle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionHandle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * REQUIRED: session_handle must be returned by a CreateSession call
   * to the same master service.
   * </pre>
   *
   * <code>optional string session_handle = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSessionHandleBytes() {
    java.lang.Object ref = sessionHandle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionHandle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEED_FIELD_NUMBER = 2;
  private java.util.List<org.tensorflow.framework.NamedTensorProto> feed_;
  /**
   * <pre>
   * Tensors to be fed in the step. Each feed is a named tensor.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
   */
  public java.util.List<org.tensorflow.framework.NamedTensorProto> getFeedList() {
    return feed_;
  }
  /**
   * <pre>
   * Tensors to be fed in the step. Each feed is a named tensor.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
   */
  public java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getFeedOrBuilderList() {
    return feed_;
  }
  /**
   * <pre>
   * Tensors to be fed in the step. Each feed is a named tensor.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
   */
  public int getFeedCount() {
    return feed_.size();
  }
  /**
   * <pre>
   * Tensors to be fed in the step. Each feed is a named tensor.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
   */
  public org.tensorflow.framework.NamedTensorProto getFeed(int index) {
    return feed_.get(index);
  }
  /**
   * <pre>
   * Tensors to be fed in the step. Each feed is a named tensor.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
   */
  public org.tensorflow.framework.NamedTensorProtoOrBuilder getFeedOrBuilder(
      int index) {
    return feed_.get(index);
  }

  public static final int FETCH_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList fetch_;
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to
   * be returned for each fetch[i] (see RunStepResponse.tensor). The
   * order of specified fetches does not change the execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFetchList() {
    return fetch_;
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to
   * be returned for each fetch[i] (see RunStepResponse.tensor). The
   * order of specified fetches does not change the execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   */
  public int getFetchCount() {
    return fetch_.size();
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to
   * be returned for each fetch[i] (see RunStepResponse.tensor). The
   * order of specified fetches does not change the execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   */
  public java.lang.String getFetch(int index) {
    return fetch_.get(index);
  }
  /**
   * <pre>
   * Fetches. A list of tensor names. The caller expects a tensor to
   * be returned for each fetch[i] (see RunStepResponse.tensor). The
   * order of specified fetches does not change the execution order.
   * </pre>
   *
   * <code>repeated string fetch = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFetchBytes(int index) {
    return fetch_.getByteString(index);
  }

  public static final int TARGET_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList target_;
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run
   * to but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTargetList() {
    return target_;
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run
   * to but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   */
  public int getTargetCount() {
    return target_.size();
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run
   * to but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   */
  public java.lang.String getTarget(int index) {
    return target_.get(index);
  }
  /**
   * <pre>
   * Target Nodes. A list of node names. The named nodes will be run
   * to but their outputs will not be fetched.
   * </pre>
   *
   * <code>repeated string target = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTargetBytes(int index) {
    return target_.getByteString(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 5;
  private org.tensorflow.framework.RunOptions options_;
  /**
   * <pre>
   * Options for the run call.
   * </pre>
   *
   * <code>optional .tensorflow.RunOptions options = 5;</code>
   */
  public boolean hasOptions() {
    return options_ != null;
  }
  /**
   * <pre>
   * Options for the run call.
   * </pre>
   *
   * <code>optional .tensorflow.RunOptions options = 5;</code>
   */
  public org.tensorflow.framework.RunOptions getOptions() {
    return options_ == null ? org.tensorflow.framework.RunOptions.getDefaultInstance() : options_;
  }
  /**
   * <pre>
   * Options for the run call.
   * </pre>
   *
   * <code>optional .tensorflow.RunOptions options = 5;</code>
   */
  public org.tensorflow.framework.RunOptionsOrBuilder getOptionsOrBuilder() {
    return getOptions();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessionHandleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionHandle_);
    }
    for (int i = 0; i < feed_.size(); i++) {
      output.writeMessage(2, feed_.get(i));
    }
    for (int i = 0; i < fetch_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fetch_.getRaw(i));
    }
    for (int i = 0; i < target_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, target_.getRaw(i));
    }
    if (options_ != null) {
      output.writeMessage(5, getOptions());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionHandleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionHandle_);
    }
    for (int i = 0; i < feed_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, feed_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fetch_.size(); i++) {
        dataSize += computeStringSizeNoTag(fetch_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFetchList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < target_.size(); i++) {
        dataSize += computeStringSizeNoTag(target_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTargetList().size();
    }
    if (options_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getOptions());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.distruntime.RunStepRequest)) {
      return super.equals(obj);
    }
    org.tensorflow.distruntime.RunStepRequest other = (org.tensorflow.distruntime.RunStepRequest) obj;

    boolean result = true;
    result = result && getSessionHandle()
        .equals(other.getSessionHandle());
    result = result && getFeedList()
        .equals(other.getFeedList());
    result = result && getFetchList()
        .equals(other.getFetchList());
    result = result && getTargetList()
        .equals(other.getTargetList());
    result = result && (hasOptions() == other.hasOptions());
    if (hasOptions()) {
      result = result && getOptions()
          .equals(other.getOptions());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSION_HANDLE_FIELD_NUMBER;
    hash = (53 * hash) + getSessionHandle().hashCode();
    if (getFeedCount() > 0) {
      hash = (37 * hash) + FEED_FIELD_NUMBER;
      hash = (53 * hash) + getFeedList().hashCode();
    }
    if (getFetchCount() > 0) {
      hash = (37 * hash) + FETCH_FIELD_NUMBER;
      hash = (53 * hash) + getFetchList().hashCode();
    }
    if (getTargetCount() > 0) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTargetList().hashCode();
    }
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.distruntime.RunStepRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.distruntime.RunStepRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.RunStepRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.RunStepRequest)
      org.tensorflow.distruntime.RunStepRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_RunStepRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_RunStepRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.distruntime.RunStepRequest.class, org.tensorflow.distruntime.RunStepRequest.Builder.class);
    }

    // Construct using org.tensorflow.distruntime.RunStepRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFeedFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      sessionHandle_ = "";

      if (feedBuilder_ == null) {
        feed_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        feedBuilder_.clear();
      }
      fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (optionsBuilder_ == null) {
        options_ = null;
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.distruntime.DistributedRuntimeProtos.internal_static_tensorflow_RunStepRequest_descriptor;
    }

    public org.tensorflow.distruntime.RunStepRequest getDefaultInstanceForType() {
      return org.tensorflow.distruntime.RunStepRequest.getDefaultInstance();
    }

    public org.tensorflow.distruntime.RunStepRequest build() {
      org.tensorflow.distruntime.RunStepRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.distruntime.RunStepRequest buildPartial() {
      org.tensorflow.distruntime.RunStepRequest result = new org.tensorflow.distruntime.RunStepRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.sessionHandle_ = sessionHandle_;
      if (feedBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          feed_ = java.util.Collections.unmodifiableList(feed_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.feed_ = feed_;
      } else {
        result.feed_ = feedBuilder_.build();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        fetch_ = fetch_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.fetch_ = fetch_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        target_ = target_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.target_ = target_;
      if (optionsBuilder_ == null) {
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.distruntime.RunStepRequest) {
        return mergeFrom((org.tensorflow.distruntime.RunStepRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.distruntime.RunStepRequest other) {
      if (other == org.tensorflow.distruntime.RunStepRequest.getDefaultInstance()) return this;
      if (!other.getSessionHandle().isEmpty()) {
        sessionHandle_ = other.sessionHandle_;
        onChanged();
      }
      if (feedBuilder_ == null) {
        if (!other.feed_.isEmpty()) {
          if (feed_.isEmpty()) {
            feed_ = other.feed_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFeedIsMutable();
            feed_.addAll(other.feed_);
          }
          onChanged();
        }
      } else {
        if (!other.feed_.isEmpty()) {
          if (feedBuilder_.isEmpty()) {
            feedBuilder_.dispose();
            feedBuilder_ = null;
            feed_ = other.feed_;
            bitField0_ = (bitField0_ & ~0x00000002);
            feedBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFeedFieldBuilder() : null;
          } else {
            feedBuilder_.addAllMessages(other.feed_);
          }
        }
      }
      if (!other.fetch_.isEmpty()) {
        if (fetch_.isEmpty()) {
          fetch_ = other.fetch_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureFetchIsMutable();
          fetch_.addAll(other.fetch_);
        }
        onChanged();
      }
      if (!other.target_.isEmpty()) {
        if (target_.isEmpty()) {
          target_ = other.target_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureTargetIsMutable();
          target_.addAll(other.target_);
        }
        onChanged();
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.distruntime.RunStepRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.distruntime.RunStepRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionHandle_ = "";
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>optional string session_handle = 1;</code>
     */
    public java.lang.String getSessionHandle() {
      java.lang.Object ref = sessionHandle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionHandle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>optional string session_handle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionHandleBytes() {
      java.lang.Object ref = sessionHandle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionHandle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>optional string session_handle = 1;</code>
     */
    public Builder setSessionHandle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionHandle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>optional string session_handle = 1;</code>
     */
    public Builder clearSessionHandle() {
      
      sessionHandle_ = getDefaultInstance().getSessionHandle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * REQUIRED: session_handle must be returned by a CreateSession call
     * to the same master service.
     * </pre>
     *
     * <code>optional string session_handle = 1;</code>
     */
    public Builder setSessionHandleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionHandle_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.tensorflow.framework.NamedTensorProto> feed_ =
      java.util.Collections.emptyList();
    private void ensureFeedIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        feed_ = new java.util.ArrayList<org.tensorflow.framework.NamedTensorProto>(feed_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder> feedBuilder_;

    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public java.util.List<org.tensorflow.framework.NamedTensorProto> getFeedList() {
      if (feedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(feed_);
      } else {
        return feedBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public int getFeedCount() {
      if (feedBuilder_ == null) {
        return feed_.size();
      } else {
        return feedBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public org.tensorflow.framework.NamedTensorProto getFeed(int index) {
      if (feedBuilder_ == null) {
        return feed_.get(index);
      } else {
        return feedBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder setFeed(
        int index, org.tensorflow.framework.NamedTensorProto value) {
      if (feedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeedIsMutable();
        feed_.set(index, value);
        onChanged();
      } else {
        feedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder setFeed(
        int index, org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (feedBuilder_ == null) {
        ensureFeedIsMutable();
        feed_.set(index, builderForValue.build());
        onChanged();
      } else {
        feedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder addFeed(org.tensorflow.framework.NamedTensorProto value) {
      if (feedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeedIsMutable();
        feed_.add(value);
        onChanged();
      } else {
        feedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder addFeed(
        int index, org.tensorflow.framework.NamedTensorProto value) {
      if (feedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeedIsMutable();
        feed_.add(index, value);
        onChanged();
      } else {
        feedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder addFeed(
        org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (feedBuilder_ == null) {
        ensureFeedIsMutable();
        feed_.add(builderForValue.build());
        onChanged();
      } else {
        feedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder addFeed(
        int index, org.tensorflow.framework.NamedTensorProto.Builder builderForValue) {
      if (feedBuilder_ == null) {
        ensureFeedIsMutable();
        feed_.add(index, builderForValue.build());
        onChanged();
      } else {
        feedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder addAllFeed(
        java.lang.Iterable<? extends org.tensorflow.framework.NamedTensorProto> values) {
      if (feedBuilder_ == null) {
        ensureFeedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feed_);
        onChanged();
      } else {
        feedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder clearFeed() {
      if (feedBuilder_ == null) {
        feed_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        feedBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public Builder removeFeed(int index) {
      if (feedBuilder_ == null) {
        ensureFeedIsMutable();
        feed_.remove(index);
        onChanged();
      } else {
        feedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder getFeedBuilder(
        int index) {
      return getFeedFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public org.tensorflow.framework.NamedTensorProtoOrBuilder getFeedOrBuilder(
        int index) {
      if (feedBuilder_ == null) {
        return feed_.get(index);  } else {
        return feedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
         getFeedOrBuilderList() {
      if (feedBuilder_ != null) {
        return feedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(feed_);
      }
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder addFeedBuilder() {
      return getFeedFieldBuilder().addBuilder(
          org.tensorflow.framework.NamedTensorProto.getDefaultInstance());
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public org.tensorflow.framework.NamedTensorProto.Builder addFeedBuilder(
        int index) {
      return getFeedFieldBuilder().addBuilder(
          index, org.tensorflow.framework.NamedTensorProto.getDefaultInstance());
    }
    /**
     * <pre>
     * Tensors to be fed in the step. Each feed is a named tensor.
     * </pre>
     *
     * <code>repeated .tensorflow.NamedTensorProto feed = 2;</code>
     */
    public java.util.List<org.tensorflow.framework.NamedTensorProto.Builder> 
         getFeedBuilderList() {
      return getFeedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder> 
        getFeedFieldBuilder() {
      if (feedBuilder_ == null) {
        feedBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.tensorflow.framework.NamedTensorProto, org.tensorflow.framework.NamedTensorProto.Builder, org.tensorflow.framework.NamedTensorProtoOrBuilder>(
                feed_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        feed_ = null;
      }
      return feedBuilder_;
    }

    private com.google.protobuf.LazyStringList fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFetchIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        fetch_ = new com.google.protobuf.LazyStringArrayList(fetch_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFetchList() {
      return fetch_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public int getFetchCount() {
      return fetch_.size();
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public java.lang.String getFetch(int index) {
      return fetch_.get(index);
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFetchBytes(int index) {
      return fetch_.getByteString(index);
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public Builder setFetch(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFetchIsMutable();
      fetch_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public Builder addFetch(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFetchIsMutable();
      fetch_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public Builder addAllFetch(
        java.lang.Iterable<java.lang.String> values) {
      ensureFetchIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fetch_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public Builder clearFetch() {
      fetch_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fetches. A list of tensor names. The caller expects a tensor to
     * be returned for each fetch[i] (see RunStepResponse.tensor). The
     * order of specified fetches does not change the execution order.
     * </pre>
     *
     * <code>repeated string fetch = 3;</code>
     */
    public Builder addFetchBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFetchIsMutable();
      fetch_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTargetIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        target_ = new com.google.protobuf.LazyStringArrayList(target_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTargetList() {
      return target_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public int getTargetCount() {
      return target_.size();
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public java.lang.String getTarget(int index) {
      return target_.get(index);
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes(int index) {
      return target_.getByteString(index);
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public Builder setTarget(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIsMutable();
      target_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public Builder addTarget(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIsMutable();
      target_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public Builder addAllTarget(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, target_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public Builder clearTarget() {
      target_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target Nodes. A list of node names. The named nodes will be run
     * to but their outputs will not be fetched.
     * </pre>
     *
     * <code>repeated string target = 4;</code>
     */
    public Builder addTargetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTargetIsMutable();
      target_.add(value);
      onChanged();
      return this;
    }

    private org.tensorflow.framework.RunOptions options_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.RunOptions, org.tensorflow.framework.RunOptions.Builder, org.tensorflow.framework.RunOptionsOrBuilder> optionsBuilder_;
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public boolean hasOptions() {
      return optionsBuilder_ != null || options_ != null;
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public org.tensorflow.framework.RunOptions getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? org.tensorflow.framework.RunOptions.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public Builder setOptions(org.tensorflow.framework.RunOptions value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
        onChanged();
      } else {
        optionsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public Builder setOptions(
        org.tensorflow.framework.RunOptions.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
        onChanged();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public Builder mergeOptions(org.tensorflow.framework.RunOptions value) {
      if (optionsBuilder_ == null) {
        if (options_ != null) {
          options_ =
            org.tensorflow.framework.RunOptions.newBuilder(options_).mergeFrom(value).buildPartial();
        } else {
          options_ = value;
        }
        onChanged();
      } else {
        optionsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = null;
        onChanged();
      } else {
        options_ = null;
        optionsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public org.tensorflow.framework.RunOptions.Builder getOptionsBuilder() {
      
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    public org.tensorflow.framework.RunOptionsOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ?
            org.tensorflow.framework.RunOptions.getDefaultInstance() : options_;
      }
    }
    /**
     * <pre>
     * Options for the run call.
     * </pre>
     *
     * <code>optional .tensorflow.RunOptions options = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.tensorflow.framework.RunOptions, org.tensorflow.framework.RunOptions.Builder, org.tensorflow.framework.RunOptionsOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.tensorflow.framework.RunOptions, org.tensorflow.framework.RunOptions.Builder, org.tensorflow.framework.RunOptionsOrBuilder>(
                getOptions(),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.RunStepRequest)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.RunStepRequest)
  private static final org.tensorflow.distruntime.RunStepRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.distruntime.RunStepRequest();
  }

  public static org.tensorflow.distruntime.RunStepRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RunStepRequest>
      PARSER = new com.google.protobuf.AbstractParser<RunStepRequest>() {
    public RunStepRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RunStepRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RunStepRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RunStepRequest> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.distruntime.RunStepRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

