// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/master.proto

package org.tensorflow.distruntime;

public interface RunStepResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunStepResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * NOTE: The order of the returned tensors may or may not match
   * the fetch order specified in RunStepRequest.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto tensor = 1;</code>
   */
  java.util.List<org.tensorflow.framework.NamedTensorProto> 
      getTensorList();
  /**
   * <pre>
   * NOTE: The order of the returned tensors may or may not match
   * the fetch order specified in RunStepRequest.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto tensor = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProto getTensor(int index);
  /**
   * <pre>
   * NOTE: The order of the returned tensors may or may not match
   * the fetch order specified in RunStepRequest.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto tensor = 1;</code>
   */
  int getTensorCount();
  /**
   * <pre>
   * NOTE: The order of the returned tensors may or may not match
   * the fetch order specified in RunStepRequest.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto tensor = 1;</code>
   */
  java.util.List<? extends org.tensorflow.framework.NamedTensorProtoOrBuilder> 
      getTensorOrBuilderList();
  /**
   * <pre>
   * NOTE: The order of the returned tensors may or may not match
   * the fetch order specified in RunStepRequest.
   * </pre>
   *
   * <code>repeated .tensorflow.NamedTensorProto tensor = 1;</code>
   */
  org.tensorflow.framework.NamedTensorProtoOrBuilder getTensorOrBuilder(
      int index);

  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>optional .tensorflow.RunMetadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>optional .tensorflow.RunMetadata metadata = 2;</code>
   */
  org.tensorflow.framework.RunMetadata getMetadata();
  /**
   * <pre>
   * Returned metadata if requested in the options.
   * </pre>
   *
   * <code>optional .tensorflow.RunMetadata metadata = 2;</code>
   */
  org.tensorflow.framework.RunMetadataOrBuilder getMetadataOrBuilder();
}
