// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/event.proto

package org.tensorflow.util;

public final class EventProtos {
  private EventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LogMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LogMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SessionLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SessionLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TaggedRunMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TaggedRunMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n tensorflow/core/util/event.proto\022\ntens" +
      "orflow\032\'tensorflow/core/framework/summar" +
      "y.proto\"\241\002\n\005Event\022\021\n\twall_time\030\001 \001(\001\022\014\n\004" +
      "step\030\002 \001(\003\022\026\n\014file_version\030\003 \001(\tH\000\022\023\n\tgr" +
      "aph_def\030\004 \001(\014H\000\022&\n\007summary\030\005 \001(\0132\023.tenso" +
      "rflow.SummaryH\000\022-\n\013log_message\030\006 \001(\0132\026.t" +
      "ensorflow.LogMessageH\000\022-\n\013session_log\030\007 " +
      "\001(\0132\026.tensorflow.SessionLogH\000\022<\n\023tagged_" +
      "run_metadata\030\010 \001(\0132\035.tensorflow.TaggedRu" +
      "nMetadataH\000B\006\n\004what\"\225\001\n\nLogMessage\022+\n\005le",
      "vel\030\001 \001(\0162\034.tensorflow.LogMessage.Level\022" +
      "\017\n\007message\030\002 \001(\t\"I\n\005Level\022\013\n\007UNKNOWN\020\000\022\t" +
      "\n\005DEBUG\020\n\022\010\n\004INFO\020\024\022\010\n\004WARN\020\036\022\t\n\005ERROR\020(" +
      "\022\t\n\005FATAL\0202\"\266\001\n\nSessionLog\0224\n\006status\030\001 \001" +
      "(\0162$.tensorflow.SessionLog.SessionStatus" +
      "\022\027\n\017checkpoint_path\030\002 \001(\t\022\013\n\003msg\030\003 \001(\t\"L" +
      "\n\rSessionStatus\022\026\n\022STATUS_UNSPECIFIED\020\000\022" +
      "\t\n\005START\020\001\022\010\n\004STOP\020\002\022\016\n\nCHECKPOINT\020\003\"6\n\021" +
      "TaggedRunMetadata\022\013\n\003tag\030\001 \001(\t\022\024\n\014run_me" +
      "tadata\030\002 \001(\014B\'\n\023org.tensorflow.utilB\013Eve",
      "ntProtosP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.framework.SummaryProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_Event_descriptor,
        new java.lang.String[] { "WallTime", "Step", "FileVersion", "GraphDef", "Summary", "LogMessage", "SessionLog", "TaggedRunMetadata", "What", });
    internal_static_tensorflow_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LogMessage_descriptor,
        new java.lang.String[] { "Level", "Message", });
    internal_static_tensorflow_SessionLog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_SessionLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SessionLog_descriptor,
        new java.lang.String[] { "Status", "CheckpointPath", "Msg", });
    internal_static_tensorflow_TaggedRunMetadata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_TaggedRunMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TaggedRunMetadata_descriptor,
        new java.lang.String[] { "Tag", "RunMetadata", });
    org.tensorflow.framework.SummaryProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
