// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/event.proto

package org.tensorflow.util;

public interface LogMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.LogMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.LogMessage.Level level = 1;</code>
   */
  int getLevelValue();
  /**
   * <code>optional .tensorflow.LogMessage.Level level = 1;</code>
   */
  org.tensorflow.util.LogMessage.Level getLevel();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
