// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/test_log.proto

package org.tensorflow.util.testlog;

/**
 * Protobuf type {@code tensorflow.BuildConfiguration}
 */
public  final class BuildConfiguration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.BuildConfiguration)
    BuildConfigurationOrBuilder {
  // Use BuildConfiguration.newBuilder() to construct.
  private BuildConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BuildConfiguration() {
    mode_ = "";
    ccFlags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    opts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BuildConfiguration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              ccFlags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            ccFlags_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              opts_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            opts_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        ccFlags_ = ccFlags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        opts_ = opts_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_BuildConfiguration_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_BuildConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.util.testlog.BuildConfiguration.class, org.tensorflow.util.testlog.BuildConfiguration.Builder.class);
  }

  private int bitField0_;
  public static final int MODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object mode_;
  /**
   * <pre>
   * opt, dbg, etc
   * </pre>
   *
   * <code>optional string mode = 1;</code>
   */
  public java.lang.String getMode() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * opt, dbg, etc
   * </pre>
   *
   * <code>optional string mode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getModeBytes() {
    java.lang.Object ref = mode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CC_FLAGS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList ccFlags_;
  /**
   * <pre>
   * CC compiler flags, if known
   * </pre>
   *
   * <code>repeated string cc_flags = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCcFlagsList() {
    return ccFlags_;
  }
  /**
   * <pre>
   * CC compiler flags, if known
   * </pre>
   *
   * <code>repeated string cc_flags = 2;</code>
   */
  public int getCcFlagsCount() {
    return ccFlags_.size();
  }
  /**
   * <pre>
   * CC compiler flags, if known
   * </pre>
   *
   * <code>repeated string cc_flags = 2;</code>
   */
  public java.lang.String getCcFlags(int index) {
    return ccFlags_.get(index);
  }
  /**
   * <pre>
   * CC compiler flags, if known
   * </pre>
   *
   * <code>repeated string cc_flags = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCcFlagsBytes(int index) {
    return ccFlags_.getByteString(index);
  }

  public static final int OPTS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList opts_;
  /**
   * <pre>
   * Bazel compilation options, if known
   * </pre>
   *
   * <code>repeated string opts = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getOptsList() {
    return opts_;
  }
  /**
   * <pre>
   * Bazel compilation options, if known
   * </pre>
   *
   * <code>repeated string opts = 3;</code>
   */
  public int getOptsCount() {
    return opts_.size();
  }
  /**
   * <pre>
   * Bazel compilation options, if known
   * </pre>
   *
   * <code>repeated string opts = 3;</code>
   */
  public java.lang.String getOpts(int index) {
    return opts_.get(index);
  }
  /**
   * <pre>
   * Bazel compilation options, if known
   * </pre>
   *
   * <code>repeated string opts = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOptsBytes(int index) {
    return opts_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getModeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mode_);
    }
    for (int i = 0; i < ccFlags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ccFlags_.getRaw(i));
    }
    for (int i = 0; i < opts_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, opts_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getModeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mode_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ccFlags_.size(); i++) {
        dataSize += computeStringSizeNoTag(ccFlags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCcFlagsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < opts_.size(); i++) {
        dataSize += computeStringSizeNoTag(opts_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOptsList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.util.testlog.BuildConfiguration)) {
      return super.equals(obj);
    }
    org.tensorflow.util.testlog.BuildConfiguration other = (org.tensorflow.util.testlog.BuildConfiguration) obj;

    boolean result = true;
    result = result && getMode()
        .equals(other.getMode());
    result = result && getCcFlagsList()
        .equals(other.getCcFlagsList());
    result = result && getOptsList()
        .equals(other.getOptsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode().hashCode();
    if (getCcFlagsCount() > 0) {
      hash = (37 * hash) + CC_FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getCcFlagsList().hashCode();
    }
    if (getOptsCount() > 0) {
      hash = (37 * hash) + OPTS_FIELD_NUMBER;
      hash = (53 * hash) + getOptsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.BuildConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.util.testlog.BuildConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.BuildConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.BuildConfiguration)
      org.tensorflow.util.testlog.BuildConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_BuildConfiguration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_BuildConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.util.testlog.BuildConfiguration.class, org.tensorflow.util.testlog.BuildConfiguration.Builder.class);
    }

    // Construct using org.tensorflow.util.testlog.BuildConfiguration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mode_ = "";

      ccFlags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      opts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_BuildConfiguration_descriptor;
    }

    public org.tensorflow.util.testlog.BuildConfiguration getDefaultInstanceForType() {
      return org.tensorflow.util.testlog.BuildConfiguration.getDefaultInstance();
    }

    public org.tensorflow.util.testlog.BuildConfiguration build() {
      org.tensorflow.util.testlog.BuildConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.util.testlog.BuildConfiguration buildPartial() {
      org.tensorflow.util.testlog.BuildConfiguration result = new org.tensorflow.util.testlog.BuildConfiguration(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.mode_ = mode_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        ccFlags_ = ccFlags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.ccFlags_ = ccFlags_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        opts_ = opts_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.opts_ = opts_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.util.testlog.BuildConfiguration) {
        return mergeFrom((org.tensorflow.util.testlog.BuildConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.util.testlog.BuildConfiguration other) {
      if (other == org.tensorflow.util.testlog.BuildConfiguration.getDefaultInstance()) return this;
      if (!other.getMode().isEmpty()) {
        mode_ = other.mode_;
        onChanged();
      }
      if (!other.ccFlags_.isEmpty()) {
        if (ccFlags_.isEmpty()) {
          ccFlags_ = other.ccFlags_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCcFlagsIsMutable();
          ccFlags_.addAll(other.ccFlags_);
        }
        onChanged();
      }
      if (!other.opts_.isEmpty()) {
        if (opts_.isEmpty()) {
          opts_ = other.opts_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureOptsIsMutable();
          opts_.addAll(other.opts_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.util.testlog.BuildConfiguration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.util.testlog.BuildConfiguration) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object mode_ = "";
    /**
     * <pre>
     * opt, dbg, etc
     * </pre>
     *
     * <code>optional string mode = 1;</code>
     */
    public java.lang.String getMode() {
      java.lang.Object ref = mode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * opt, dbg, etc
     * </pre>
     *
     * <code>optional string mode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModeBytes() {
      java.lang.Object ref = mode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * opt, dbg, etc
     * </pre>
     *
     * <code>optional string mode = 1;</code>
     */
    public Builder setMode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * opt, dbg, etc
     * </pre>
     *
     * <code>optional string mode = 1;</code>
     */
    public Builder clearMode() {
      
      mode_ = getDefaultInstance().getMode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * opt, dbg, etc
     * </pre>
     *
     * <code>optional string mode = 1;</code>
     */
    public Builder setModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mode_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList ccFlags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCcFlagsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        ccFlags_ = new com.google.protobuf.LazyStringArrayList(ccFlags_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCcFlagsList() {
      return ccFlags_.getUnmodifiableView();
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public int getCcFlagsCount() {
      return ccFlags_.size();
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public java.lang.String getCcFlags(int index) {
      return ccFlags_.get(index);
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCcFlagsBytes(int index) {
      return ccFlags_.getByteString(index);
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public Builder setCcFlags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCcFlagsIsMutable();
      ccFlags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public Builder addCcFlags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCcFlagsIsMutable();
      ccFlags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public Builder addAllCcFlags(
        java.lang.Iterable<java.lang.String> values) {
      ensureCcFlagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ccFlags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public Builder clearCcFlags() {
      ccFlags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CC compiler flags, if known
     * </pre>
     *
     * <code>repeated string cc_flags = 2;</code>
     */
    public Builder addCcFlagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCcFlagsIsMutable();
      ccFlags_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList opts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOptsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        opts_ = new com.google.protobuf.LazyStringArrayList(opts_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOptsList() {
      return opts_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public int getOptsCount() {
      return opts_.size();
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public java.lang.String getOpts(int index) {
      return opts_.get(index);
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOptsBytes(int index) {
      return opts_.getByteString(index);
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public Builder setOpts(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOptsIsMutable();
      opts_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public Builder addOpts(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOptsIsMutable();
      opts_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public Builder addAllOpts(
        java.lang.Iterable<java.lang.String> values) {
      ensureOptsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, opts_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public Builder clearOpts() {
      opts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Bazel compilation options, if known
     * </pre>
     *
     * <code>repeated string opts = 3;</code>
     */
    public Builder addOptsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOptsIsMutable();
      opts_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.BuildConfiguration)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.BuildConfiguration)
  private static final org.tensorflow.util.testlog.BuildConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.util.testlog.BuildConfiguration();
  }

  public static org.tensorflow.util.testlog.BuildConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BuildConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<BuildConfiguration>() {
    public BuildConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildConfiguration(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BuildConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BuildConfiguration> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.util.testlog.BuildConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

