// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/test_log.proto

package org.tensorflow.util.testlog;

/**
 * Protobuf type {@code tensorflow.CPUInfo}
 */
public  final class CPUInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.CPUInfo)
    CPUInfoOrBuilder {
  // Use CPUInfo.newBuilder() to construct.
  private CPUInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CPUInfo() {
    numCores_ = 0L;
    numCoresAllowed_ = 0L;
    mhzPerCpu_ = 0D;
    cpuInfo_ = "";
    cpuGovernor_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CPUInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            numCores_ = input.readInt64();
            break;
          }
          case 16: {

            numCoresAllowed_ = input.readInt64();
            break;
          }
          case 25: {

            mhzPerCpu_ = input.readDouble();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cpuInfo_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            cpuGovernor_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              cacheSize_ = com.google.protobuf.MapField.newMapField(
                  CacheSizeDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
            cacheSize = input.readMessage(
                CacheSizeDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            cacheSize_.getMutableMap().put(cacheSize.getKey(), cacheSize.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetCacheSize();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.util.testlog.CPUInfo.class, org.tensorflow.util.testlog.CPUInfo.Builder.class);
  }

  private int bitField0_;
  public static final int NUM_CORES_FIELD_NUMBER = 1;
  private long numCores_;
  /**
   * <code>optional int64 num_cores = 1;</code>
   */
  public long getNumCores() {
    return numCores_;
  }

  public static final int NUM_CORES_ALLOWED_FIELD_NUMBER = 2;
  private long numCoresAllowed_;
  /**
   * <code>optional int64 num_cores_allowed = 2;</code>
   */
  public long getNumCoresAllowed() {
    return numCoresAllowed_;
  }

  public static final int MHZ_PER_CPU_FIELD_NUMBER = 3;
  private double mhzPerCpu_;
  /**
   * <pre>
   * How fast are these cpus?
   * </pre>
   *
   * <code>optional double mhz_per_cpu = 3;</code>
   */
  public double getMhzPerCpu() {
    return mhzPerCpu_;
  }

  public static final int CPU_INFO_FIELD_NUMBER = 4;
  private volatile java.lang.Object cpuInfo_;
  /**
   * <pre>
   * Additional cpu information. For example,
   * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
   * </pre>
   *
   * <code>optional string cpu_info = 4;</code>
   */
  public java.lang.String getCpuInfo() {
    java.lang.Object ref = cpuInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpuInfo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Additional cpu information. For example,
   * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
   * </pre>
   *
   * <code>optional string cpu_info = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCpuInfoBytes() {
    java.lang.Object ref = cpuInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpuInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_GOVERNOR_FIELD_NUMBER = 5;
  private volatile java.lang.Object cpuGovernor_;
  /**
   * <pre>
   * What kind of cpu scaling is enabled on the host.
   * Examples include "performance", "ondemand", "conservative", "mixed".
   * </pre>
   *
   * <code>optional string cpu_governor = 5;</code>
   */
  public java.lang.String getCpuGovernor() {
    java.lang.Object ref = cpuGovernor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpuGovernor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * What kind of cpu scaling is enabled on the host.
   * Examples include "performance", "ondemand", "conservative", "mixed".
   * </pre>
   *
   * <code>optional string cpu_governor = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCpuGovernorBytes() {
    java.lang.Object ref = cpuGovernor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpuGovernor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CACHE_SIZE_FIELD_NUMBER = 6;
  private static final class CacheSizeDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_CacheSizeEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> cacheSize_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetCacheSize() {
    if (cacheSize_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CacheSizeDefaultEntryHolder.defaultEntry);
    }
    return cacheSize_;
  }

  public int getCacheSizeCount() {
    return internalGetCacheSize().getMap().size();
  }
  /**
   * <pre>
   * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
   * </pre>
   *
   * <code>map&lt;string, int64&gt; cache_size = 6;</code>
   */

  public boolean containsCacheSize(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetCacheSize().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCacheSizeMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getCacheSize() {
    return getCacheSizeMap();
  }
  /**
   * <pre>
   * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
   * </pre>
   *
   * <code>map&lt;string, int64&gt; cache_size = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Long> getCacheSizeMap() {
    return internalGetCacheSize().getMap();
  }
  /**
   * <pre>
   * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
   * </pre>
   *
   * <code>map&lt;string, int64&gt; cache_size = 6;</code>
   */

  public long getCacheSizeOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCacheSize().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
   * </pre>
   *
   * <code>map&lt;string, int64&gt; cache_size = 6;</code>
   */

  public long getCacheSizeOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCacheSize().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numCores_ != 0L) {
      output.writeInt64(1, numCores_);
    }
    if (numCoresAllowed_ != 0L) {
      output.writeInt64(2, numCoresAllowed_);
    }
    if (mhzPerCpu_ != 0D) {
      output.writeDouble(3, mhzPerCpu_);
    }
    if (!getCpuInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cpuInfo_);
    }
    if (!getCpuGovernorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cpuGovernor_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetCacheSize().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      cacheSize = CacheSizeDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(6, cacheSize);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numCores_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, numCores_);
    }
    if (numCoresAllowed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, numCoresAllowed_);
    }
    if (mhzPerCpu_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, mhzPerCpu_);
    }
    if (!getCpuInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cpuInfo_);
    }
    if (!getCpuGovernorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cpuGovernor_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetCacheSize().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      cacheSize = CacheSizeDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, cacheSize);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tensorflow.util.testlog.CPUInfo)) {
      return super.equals(obj);
    }
    org.tensorflow.util.testlog.CPUInfo other = (org.tensorflow.util.testlog.CPUInfo) obj;

    boolean result = true;
    result = result && (getNumCores()
        == other.getNumCores());
    result = result && (getNumCoresAllowed()
        == other.getNumCoresAllowed());
    result = result && (
        java.lang.Double.doubleToLongBits(getMhzPerCpu())
        == java.lang.Double.doubleToLongBits(
            other.getMhzPerCpu()));
    result = result && getCpuInfo()
        .equals(other.getCpuInfo());
    result = result && getCpuGovernor()
        .equals(other.getCpuGovernor());
    result = result && internalGetCacheSize().equals(
        other.internalGetCacheSize());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + NUM_CORES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumCores());
    hash = (37 * hash) + NUM_CORES_ALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumCoresAllowed());
    hash = (37 * hash) + MHZ_PER_CPU_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMhzPerCpu()));
    hash = (37 * hash) + CPU_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getCpuInfo().hashCode();
    hash = (37 * hash) + CPU_GOVERNOR_FIELD_NUMBER;
    hash = (53 * hash) + getCpuGovernor().hashCode();
    if (!internalGetCacheSize().getMap().isEmpty()) {
      hash = (37 * hash) + CACHE_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCacheSize().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tensorflow.util.testlog.CPUInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.util.testlog.CPUInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.CPUInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.CPUInfo)
      org.tensorflow.util.testlog.CPUInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetCacheSize();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableCacheSize();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.util.testlog.CPUInfo.class, org.tensorflow.util.testlog.CPUInfo.Builder.class);
    }

    // Construct using org.tensorflow.util.testlog.CPUInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      numCores_ = 0L;

      numCoresAllowed_ = 0L;

      mhzPerCpu_ = 0D;

      cpuInfo_ = "";

      cpuGovernor_ = "";

      internalGetMutableCacheSize().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.util.testlog.TestLogProtos.internal_static_tensorflow_CPUInfo_descriptor;
    }

    public org.tensorflow.util.testlog.CPUInfo getDefaultInstanceForType() {
      return org.tensorflow.util.testlog.CPUInfo.getDefaultInstance();
    }

    public org.tensorflow.util.testlog.CPUInfo build() {
      org.tensorflow.util.testlog.CPUInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.util.testlog.CPUInfo buildPartial() {
      org.tensorflow.util.testlog.CPUInfo result = new org.tensorflow.util.testlog.CPUInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.numCores_ = numCores_;
      result.numCoresAllowed_ = numCoresAllowed_;
      result.mhzPerCpu_ = mhzPerCpu_;
      result.cpuInfo_ = cpuInfo_;
      result.cpuGovernor_ = cpuGovernor_;
      result.cacheSize_ = internalGetCacheSize();
      result.cacheSize_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.util.testlog.CPUInfo) {
        return mergeFrom((org.tensorflow.util.testlog.CPUInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.util.testlog.CPUInfo other) {
      if (other == org.tensorflow.util.testlog.CPUInfo.getDefaultInstance()) return this;
      if (other.getNumCores() != 0L) {
        setNumCores(other.getNumCores());
      }
      if (other.getNumCoresAllowed() != 0L) {
        setNumCoresAllowed(other.getNumCoresAllowed());
      }
      if (other.getMhzPerCpu() != 0D) {
        setMhzPerCpu(other.getMhzPerCpu());
      }
      if (!other.getCpuInfo().isEmpty()) {
        cpuInfo_ = other.cpuInfo_;
        onChanged();
      }
      if (!other.getCpuGovernor().isEmpty()) {
        cpuGovernor_ = other.cpuGovernor_;
        onChanged();
      }
      internalGetMutableCacheSize().mergeFrom(
          other.internalGetCacheSize());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.util.testlog.CPUInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.util.testlog.CPUInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long numCores_ ;
    /**
     * <code>optional int64 num_cores = 1;</code>
     */
    public long getNumCores() {
      return numCores_;
    }
    /**
     * <code>optional int64 num_cores = 1;</code>
     */
    public Builder setNumCores(long value) {
      
      numCores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 num_cores = 1;</code>
     */
    public Builder clearNumCores() {
      
      numCores_ = 0L;
      onChanged();
      return this;
    }

    private long numCoresAllowed_ ;
    /**
     * <code>optional int64 num_cores_allowed = 2;</code>
     */
    public long getNumCoresAllowed() {
      return numCoresAllowed_;
    }
    /**
     * <code>optional int64 num_cores_allowed = 2;</code>
     */
    public Builder setNumCoresAllowed(long value) {
      
      numCoresAllowed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 num_cores_allowed = 2;</code>
     */
    public Builder clearNumCoresAllowed() {
      
      numCoresAllowed_ = 0L;
      onChanged();
      return this;
    }

    private double mhzPerCpu_ ;
    /**
     * <pre>
     * How fast are these cpus?
     * </pre>
     *
     * <code>optional double mhz_per_cpu = 3;</code>
     */
    public double getMhzPerCpu() {
      return mhzPerCpu_;
    }
    /**
     * <pre>
     * How fast are these cpus?
     * </pre>
     *
     * <code>optional double mhz_per_cpu = 3;</code>
     */
    public Builder setMhzPerCpu(double value) {
      
      mhzPerCpu_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How fast are these cpus?
     * </pre>
     *
     * <code>optional double mhz_per_cpu = 3;</code>
     */
    public Builder clearMhzPerCpu() {
      
      mhzPerCpu_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object cpuInfo_ = "";
    /**
     * <pre>
     * Additional cpu information. For example,
     * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
     * </pre>
     *
     * <code>optional string cpu_info = 4;</code>
     */
    public java.lang.String getCpuInfo() {
      java.lang.Object ref = cpuInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Additional cpu information. For example,
     * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
     * </pre>
     *
     * <code>optional string cpu_info = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCpuInfoBytes() {
      java.lang.Object ref = cpuInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Additional cpu information. For example,
     * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
     * </pre>
     *
     * <code>optional string cpu_info = 4;</code>
     */
    public Builder setCpuInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cpuInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Additional cpu information. For example,
     * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
     * </pre>
     *
     * <code>optional string cpu_info = 4;</code>
     */
    public Builder clearCpuInfo() {
      
      cpuInfo_ = getDefaultInstance().getCpuInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Additional cpu information. For example,
     * Intel Ivybridge with HyperThreading (24 cores) dL1:32KB dL2:256KB dL3:30MB
     * </pre>
     *
     * <code>optional string cpu_info = 4;</code>
     */
    public Builder setCpuInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cpuInfo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cpuGovernor_ = "";
    /**
     * <pre>
     * What kind of cpu scaling is enabled on the host.
     * Examples include "performance", "ondemand", "conservative", "mixed".
     * </pre>
     *
     * <code>optional string cpu_governor = 5;</code>
     */
    public java.lang.String getCpuGovernor() {
      java.lang.Object ref = cpuGovernor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuGovernor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * What kind of cpu scaling is enabled on the host.
     * Examples include "performance", "ondemand", "conservative", "mixed".
     * </pre>
     *
     * <code>optional string cpu_governor = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCpuGovernorBytes() {
      java.lang.Object ref = cpuGovernor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuGovernor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * What kind of cpu scaling is enabled on the host.
     * Examples include "performance", "ondemand", "conservative", "mixed".
     * </pre>
     *
     * <code>optional string cpu_governor = 5;</code>
     */
    public Builder setCpuGovernor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cpuGovernor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What kind of cpu scaling is enabled on the host.
     * Examples include "performance", "ondemand", "conservative", "mixed".
     * </pre>
     *
     * <code>optional string cpu_governor = 5;</code>
     */
    public Builder clearCpuGovernor() {
      
      cpuGovernor_ = getDefaultInstance().getCpuGovernor();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * What kind of cpu scaling is enabled on the host.
     * Examples include "performance", "ondemand", "conservative", "mixed".
     * </pre>
     *
     * <code>optional string cpu_governor = 5;</code>
     */
    public Builder setCpuGovernorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cpuGovernor_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> cacheSize_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetCacheSize() {
      if (cacheSize_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CacheSizeDefaultEntryHolder.defaultEntry);
      }
      return cacheSize_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMutableCacheSize() {
      onChanged();;
      if (cacheSize_ == null) {
        cacheSize_ = com.google.protobuf.MapField.newMapField(
            CacheSizeDefaultEntryHolder.defaultEntry);
      }
      if (!cacheSize_.isMutable()) {
        cacheSize_ = cacheSize_.copy();
      }
      return cacheSize_;
    }

    public int getCacheSizeCount() {
      return internalGetCacheSize().getMap().size();
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public boolean containsCacheSize(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCacheSize().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCacheSizeMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getCacheSize() {
      return getCacheSizeMap();
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Long> getCacheSizeMap() {
      return internalGetCacheSize().getMap();
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public long getCacheSizeOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCacheSize().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public long getCacheSizeOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetCacheSize().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearCacheSize() {
      getMutableCacheSize().clear();
      return this;
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public Builder removeCacheSize(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutableCacheSize().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
    getMutableCacheSize() {
      return internalGetMutableCacheSize().getMutableMap();
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */
    public Builder putCacheSize(
        java.lang.String key,
        long value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      getMutableCacheSize().put(key, value);
      return this;
    }
    /**
     * <pre>
     * Cache sizes (in bytes), e.g. "L2": 262144 (for 256KB)
     * </pre>
     *
     * <code>map&lt;string, int64&gt; cache_size = 6;</code>
     */

    public Builder putAllCacheSize(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      getMutableCacheSize().putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.CPUInfo)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.CPUInfo)
  private static final org.tensorflow.util.testlog.CPUInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.util.testlog.CPUInfo();
  }

  public static org.tensorflow.util.testlog.CPUInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CPUInfo>
      PARSER = new com.google.protobuf.AbstractParser<CPUInfo>() {
    public CPUInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPUInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CPUInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CPUInfo> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.util.testlog.CPUInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

