// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/test_log.proto

package org.tensorflow.util.testlog;

public interface RunConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RunConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string argument = 1;</code>
   */
  java.util.List<java.lang.String>
      getArgumentList();
  /**
   * <code>repeated string argument = 1;</code>
   */
  int getArgumentCount();
  /**
   * <code>repeated string argument = 1;</code>
   */
  java.lang.String getArgument(int index);
  /**
   * <code>repeated string argument = 1;</code>
   */
  com.google.protobuf.ByteString
      getArgumentBytes(int index);
}
