// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/test_log.proto

package org.tensorflow.util.testlog;

public interface TestResultsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.TestResults)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The target of the run, e.g.:
   *  //tensorflow/core:kernels_adjust_contrast_op_benchmark_test
   * </pre>
   *
   * <code>optional string target = 1;</code>
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * The target of the run, e.g.:
   *  //tensorflow/core:kernels_adjust_contrast_op_benchmark_test
   * </pre>
   *
   * <code>optional string target = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <pre>
   * The list of tests or benchmarks in this run.
   * </pre>
   *
   * <code>optional .tensorflow.BenchmarkEntries entries = 2;</code>
   */
  boolean hasEntries();
  /**
   * <pre>
   * The list of tests or benchmarks in this run.
   * </pre>
   *
   * <code>optional .tensorflow.BenchmarkEntries entries = 2;</code>
   */
  org.tensorflow.util.testlog.BenchmarkEntries getEntries();
  /**
   * <pre>
   * The list of tests or benchmarks in this run.
   * </pre>
   *
   * <code>optional .tensorflow.BenchmarkEntries entries = 2;</code>
   */
  org.tensorflow.util.testlog.BenchmarkEntriesOrBuilder getEntriesOrBuilder();

  /**
   * <pre>
   * The configuration of the build (compiled opt? with cuda? any copts?)
   * </pre>
   *
   * <code>optional .tensorflow.BuildConfiguration build_configuration = 3;</code>
   */
  boolean hasBuildConfiguration();
  /**
   * <pre>
   * The configuration of the build (compiled opt? with cuda? any copts?)
   * </pre>
   *
   * <code>optional .tensorflow.BuildConfiguration build_configuration = 3;</code>
   */
  org.tensorflow.util.testlog.BuildConfiguration getBuildConfiguration();
  /**
   * <pre>
   * The configuration of the build (compiled opt? with cuda? any copts?)
   * </pre>
   *
   * <code>optional .tensorflow.BuildConfiguration build_configuration = 3;</code>
   */
  org.tensorflow.util.testlog.BuildConfigurationOrBuilder getBuildConfigurationOrBuilder();

  /**
   * <pre>
   * The commit id (git hash or changelist)
   * </pre>
   *
   * <code>optional .tensorflow.CommitId commit_id = 4;</code>
   */
  boolean hasCommitId();
  /**
   * <pre>
   * The commit id (git hash or changelist)
   * </pre>
   *
   * <code>optional .tensorflow.CommitId commit_id = 4;</code>
   */
  org.tensorflow.util.testlog.CommitId getCommitId();
  /**
   * <pre>
   * The commit id (git hash or changelist)
   * </pre>
   *
   * <code>optional .tensorflow.CommitId commit_id = 4;</code>
   */
  org.tensorflow.util.testlog.CommitIdOrBuilder getCommitIdOrBuilder();

  /**
   * <pre>
   * The time the run started (in seconds of UTC time since Unix epoch)
   * </pre>
   *
   * <code>optional int64 start_time = 5;</code>
   */
  long getStartTime();

  /**
   * <pre>
   * The amount of time the total run took (wall time in seconds)
   * </pre>
   *
   * <code>optional double run_time = 6;</code>
   */
  double getRunTime();

  /**
   * <pre>
   * Machine-specific parameters (Platform and CPU info)
   * </pre>
   *
   * <code>optional .tensorflow.MachineConfiguration machine_configuration = 7;</code>
   */
  boolean hasMachineConfiguration();
  /**
   * <pre>
   * Machine-specific parameters (Platform and CPU info)
   * </pre>
   *
   * <code>optional .tensorflow.MachineConfiguration machine_configuration = 7;</code>
   */
  org.tensorflow.util.testlog.MachineConfiguration getMachineConfiguration();
  /**
   * <pre>
   * Machine-specific parameters (Platform and CPU info)
   * </pre>
   *
   * <code>optional .tensorflow.MachineConfiguration machine_configuration = 7;</code>
   */
  org.tensorflow.util.testlog.MachineConfigurationOrBuilder getMachineConfigurationOrBuilder();

  /**
   * <pre>
   * Run-specific parameters (arguments, etc)
   * </pre>
   *
   * <code>optional .tensorflow.RunConfiguration run_configuration = 8;</code>
   */
  boolean hasRunConfiguration();
  /**
   * <pre>
   * Run-specific parameters (arguments, etc)
   * </pre>
   *
   * <code>optional .tensorflow.RunConfiguration run_configuration = 8;</code>
   */
  org.tensorflow.util.testlog.RunConfiguration getRunConfiguration();
  /**
   * <pre>
   * Run-specific parameters (arguments, etc)
   * </pre>
   *
   * <code>optional .tensorflow.RunConfiguration run_configuration = 8;</code>
   */
  org.tensorflow.util.testlog.RunConfigurationOrBuilder getRunConfigurationOrBuilder();
}
